apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: view
build:
  artifacts:
    - image: view-app
      context: ../lib/app
      docker:
        dockerfile: Dockerfile
  tagPolicy:
    gitCommit:
      variant: AbbrevCommitSha
  local:
    useBuildkit: true
    push: false
deploy:
  helm:
    releases:
      - name: view-app
        chartPath: ../lib/app/helm
        artifactOverrides:
          image: view-app