apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: app
deploy:
  helm:
    releases:
      - name: mock
        chartPath: ../lib/wiremock
        version: 0.1.0
        setValues:
          name: mock-api
          port: 13000