apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: app
build:
  artifacts:
    - image: view-app
      context: ../lib/app
      docker:
        dockerfile: Dockerfile
    - image: datastore
      context: ../lib/db
      docker:
        dockerfile: Dockerfile
  tagPolicy:
    gitCommit:
      variant: AbbrevCommitSha
  local:
    push: false
    useBuildkit: true
deploy:
  helm:
    releases:
      - name: view-app
        chartPath: ../lib/app/helm
        setValueTemplates:
          image: '{{ .IMAGE_FULLY_QUALIFIED_view_app }}'
      - name: datastore
        chartPath: ../lib/db/helm
        setValueTemplates:
          image: '{{.IMAGE_FULLY_QUALIFIED_datastore}}'
      - name: proxy
        chartPath: ../lib/proxy
      - name: mock
        chartPath: ../lib/wiremock
        setValues:
          name: mock-api
          port: "13000"
profiles:
  - name: deps-only
    activation:
      - command: dev
    patches:
      - op: remove
        path: /deploy/helm/releases/0
      - op: remove
        path: /build/artifacts/0
  - name: app-only
    patches:
      - op: remove
        path: /deploy/helm/releases/3
      - op: remove
        path: /deploy/helm/releases/2
      - op: remove
        path: /deploy/helm/releases/1
