apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: view-app
  name: view-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: view-app
  template:
    metadata:
      labels:
        app: view-app
    spec:
      containers:
      - image: {{ .Values.image }}
        name: view-app
