apiVersion: v1
kind: Service
metadata:
  labels:
    app: view-app
  name: view-app
spec:
  ports:
  - name: 14000-80
    port: 14000
    protocol: TCP
    targetPort: 80
  selector:
    app: view-app
  type: ClusterIP
